version: '3.8'

services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  postgres:
    image: "postgres"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
      
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  worker:
    build:
      context: .
      dockerfile: docker/Dockerfile.worker
    depends_on:
      - api

  streamlit:
    image: streamlit/streamlit
    volumes:
      - ./ui:/ui
    ports:
      - "8501:8501"
    command: streamlit run /ui/streamlit_app.py

volumes:
  postgres_data: