# docker/Dockerfile.worker
FROM python:3.9-slim

WORKDIR /app

COPY ./app /app
COPY ./requirements.txt /app

RUN pip install -r requirements.txt

CMD ["celery", "-A", "core.celery_app.celery", "worker", "--loglevel=info"]